-- Migration 010: the personal Facebook profile
-- Run once in the Neon SQL editor against PRODUCTION (ep-small-mud-az5opu7m),
-- BEFORE deploying /api/ingest/personal. Safe to run more than once.
--
-- The personal profile has no API. A local scraper reads three screens and
-- sends one payload per run, a "collection":
--   timeline  the figures shown on a post on the profile
--   library   the Content Library table in the professional dashboard
--   audience  the Audience screen: exact follower total, 28 day follows
--
-- What this adds:
--   1. posts.platform accepts 'facebook-personal', and content_posts excludes
--      it, so no median, cohort, format alert or leaderboard ever sees these
--      rows. post_metrics is not touched and is never written for them.
--   2. audience_snapshots.source accepts 'scrape'.
--   3. profile_collections, profile_posts, profile_metrics.
--   4. Two views: the latest observation per post, and follower change.
--
-- Rules the tables hold, each of which exists because the opposite produces a
-- figure that looks real and is not:
--   - A null value is unknown. A blank or "--" is never stored as zero.
--   - Labels are Facebook's own. Viewers is stored as Viewers, never as reach.
--   - scope is 'unknown' until it is verified whether a Content Library figure
--     is a lifetime total or a total within the displayed period.
--   - Observations are append only, one set per collection. Nothing here
--     deletes, and a post that leaves the 28 day library keeps its rows.

-- 1. posts ------------------------------------------------------------------

-- The original check is inline in CREATE TABLE, so its name was generated.
-- Drop whichever check constraint mentions the column, by definition rather
-- than by a guessed name.
DO $$
DECLARE
  c RECORD;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'posts'::regclass AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%platform%'
  LOOP
    EXECUTE format('ALTER TABLE posts DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE posts ADD CONSTRAINT posts_platform_check
  CHECK (platform IN ('instagram','facebook','facebook-personal','tiktok','youtube'));

-- Posts that count. Columns are listed rather than SELECT *, so a column
-- added to posts later has to be added here on purpose.
CREATE OR REPLACE VIEW content_posts AS
  SELECT id, platform, platform_post_id, format, media_product_type, content_theme,
         published_at, caption, thumbnail_url, permalink, link_slug,
         last_synced_at, created_at
  FROM posts
  WHERE page_update IS NULL
    AND platform <> 'facebook-personal';

-- 2. audience_snapshots -----------------------------------------------------

-- Existing constraints, read from migration 002 and left as they are:
--   unique index audience_snapshots_platform_day_idx on (platform, recorded_on)
--   platform check, which already includes 'facebook-personal'
--   source check ('api','manual'), replaced below
--
-- The unique index means one row per platform per day whatever its source.
-- The scraper's upsert carries WHERE source = 'scrape', so a day held by a
-- manual row is skipped and reported. The manual entry form overwrites any
-- row for its day and sets source = 'manual', so a manual figure always wins.
DO $$
DECLARE
  c RECORD;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'audience_snapshots'::regclass AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%source%'
  LOOP
    EXECUTE format('ALTER TABLE audience_snapshots DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE audience_snapshots ADD CONSTRAINT audience_snapshots_source_check
  CHECK (source IN ('api','manual','scrape'));

-- 3. Collections ------------------------------------------------------------

-- One row per scraper run. collection_id is generated by the scraper once per
-- run and travels with the payload, so the same payload sent again is a retry
-- and a later run is a new collection. payload_hash tells a true retry from a
-- different payload reusing an ID, which is refused.
CREATE TABLE IF NOT EXISTS profile_collections (
  id                    SERIAL       PRIMARY KEY,
  collection_id         UUID         NOT NULL UNIQUE,
  payload_hash          CHAR(64)     NOT NULL,
  collected_at          TIMESTAMPTZ  NOT NULL,
  collected_on          DATE         NOT NULL,   -- calendar day in `timezone`
  timezone              TEXT         NOT NULL,   -- zone the browser displayed times in
  timezone_check        TEXT         NOT NULL CHECK (timezone_check IN ('consistent','unverified')),
  timeline_status       TEXT         NOT NULL CHECK (timeline_status IN ('ok','failed')),
  library_status        TEXT         NOT NULL CHECK (library_status  IN ('ok','failed')),
  audience_status       TEXT         NOT NULL CHECK (audience_status IN ('ok','failed')),
  library_period_label  TEXT,                    -- as displayed, e.g. "Last 28 days: Sep 6 - Oct 4"
  library_period_start  DATE,
  library_period_end    DATE,
  audience_period_label TEXT,
  audience_period_start DATE,
  audience_period_end   DATE,
  unmatched             JSONB        NOT NULL DEFAULT '[]',  -- rows the scraper would not join
  received_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS profile_collections_collected_at_idx
  ON profile_collections (collected_at DESC);

-- 4. Per post facts that posts has no column for ------------------------------

-- The identity of a post is posts.platform_post_id = 'personal:p<post id>' or
-- 'personal:s<story id>', both decoded from the dashboard's content_id. A
-- video ID is never an identity. It is kept in timeline_id for reference.
CREATE TABLE IF NOT EXISTS profile_posts (
  post_id                  INTEGER  PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
  kind                     TEXT     NOT NULL CHECK (kind IN ('post','story')),
  published_label          TEXT,     -- the time exactly as the Content Library showed it
  published_timezone       TEXT,     -- the zone that label was displayed in
  caption_complete         BOOLEAN,  -- true once the full caption was read. null is unknown
  timeline_id              TEXT,
  first_collection         INTEGER  NOT NULL REFERENCES profile_collections(id),
  last_library_collection  INTEGER  REFERENCES profile_collections(id),
  last_timeline_collection INTEGER  REFERENCES profile_collections(id)
);

-- 5. Observations -----------------------------------------------------------

-- One row per figure shown, per collection. post_id is null for an account
-- level figure from the Audience screen.
--
-- label is Facebook's own wording for library and audience figures. The
-- timeline shows icons, not words, so its four labels are the scraper's:
-- "Reactions" (the total beside the like button), "Reactions: <Type>",
-- "Comments" and "Shares".
--
-- raw is the text as displayed. value is null when no number was shown: raw
-- '--' is Facebook's own "no figure", and raw null is a blank. Neither is zero.
CREATE TABLE IF NOT EXISTS profile_metrics (
  id            BIGSERIAL    PRIMARY KEY,
  collection    INTEGER      NOT NULL REFERENCES profile_collections(id),
  post_id       INTEGER      REFERENCES posts(id) ON DELETE CASCADE,
  source        TEXT         NOT NULL CHECK (source IN ('timeline','library','audience')),
  label         TEXT         NOT NULL,
  raw           TEXT,
  value         NUMERIC,
  unit          TEXT         CHECK (unit IN ('count','seconds','multiple')),
  exact         BOOLEAN,     -- false for a rounded display figure such as 1.1K
  scope         TEXT         NOT NULL DEFAULT 'unknown' CHECK (scope IN ('unknown','lifetime','period')),
  period_label  TEXT,        -- the reporting period as displayed beside the figure
  period_start  DATE,
  period_end    DATE,
  collected_at  TIMESTAMPTZ  NOT NULL,
  CHECK (value IS NOT NULL OR (unit IS NULL AND exact IS NULL)),
  CHECK ((source = 'audience') = (post_id IS NULL))
);

-- The conflict key. Within one collection a post has one figure per source
-- and label, so a payload cannot store an observation twice.
CREATE UNIQUE INDEX IF NOT EXISTS profile_metrics_key
  ON profile_metrics (collection, COALESCE(post_id, 0), source, label);

CREATE INDEX IF NOT EXISTS profile_metrics_post_idx
  ON profile_metrics (post_id, source, label, collected_at DESC);

-- 6. Views ------------------------------------------------------------------

-- The most recent observation of each figure for each post. A post that has
-- left the library still appears here with its last reading and the time it
-- was taken, which is what a "last updated" label on the dashboard reads.
CREATE OR REPLACE VIEW profile_metrics_latest AS
  SELECT DISTINCT ON (COALESCE(post_id, 0), source, label)
         post_id, source, label, raw, value, unit, exact, scope,
         period_label, period_start, period_end, collected_at, collection
  FROM profile_metrics
  ORDER BY COALESCE(post_id, 0), source, label, collected_at DESC;

-- Follower change between consecutive scraped totals. Only source = 'scrape'
-- rows are exact totals read from the Audience screen. is_daily is true only
-- when the two rows are on consecutive calendar days. Across a gap, change is
-- the change over `days` days and must not be shown as a daily gain.
CREATE OR REPLACE VIEW profile_follower_changes AS
  SELECT recorded_on,
         followers,
         LAG(recorded_on) OVER w                       AS previous_on,
         LAG(followers)   OVER w                       AS previous_followers,
         followers - LAG(followers) OVER w             AS change,
         recorded_on - LAG(recorded_on) OVER w         AS days,
         (recorded_on - LAG(recorded_on) OVER w) = 1   AS is_daily
  FROM audience_snapshots
  WHERE platform = 'facebook-personal' AND source = 'scrape' AND followers IS NOT NULL
  WINDOW w AS (ORDER BY recorded_on);

-- Check the result. Both constraints should list the new value, the three
-- tables should exist and be empty, and the counts per platform should match
-- what they were before this ran, because no facebook-personal row exists yet.
SELECT conrelid::regclass AS on_table, conname, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conname IN ('posts_platform_check', 'audience_snapshots_source_check');

SELECT (SELECT COUNT(*) FROM profile_collections)::int AS collections,
       (SELECT COUNT(*) FROM profile_posts)::int       AS profile_posts,
       (SELECT COUNT(*) FROM profile_metrics)::int     AS observations;

SELECT p.platform,
       COUNT(*)::int AS posts_rows,
       (SELECT COUNT(*)::int FROM content_posts c WHERE c.platform = p.platform) AS content_posts_rows
FROM posts p
GROUP BY p.platform
ORDER BY p.platform;
